// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/asignacion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicioAsignacion_EnviarEmergencia_FullMethodName = "/asignacion.ServicioAsignacion/EnviarEmergencia"
)

// ServicioAsignacionClient is the client API for ServicioAsignacion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicioAsignacionClient interface {
	EnviarEmergencia(ctx context.Context, in *EmergenciaRequest, opts ...grpc.CallOption) (*Respuesta, error)
}

type servicioAsignacionClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioAsignacionClient(cc grpc.ClientConnInterface) ServicioAsignacionClient {
	return &servicioAsignacionClient{cc}
}

func (c *servicioAsignacionClient) EnviarEmergencia(ctx context.Context, in *EmergenciaRequest, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, ServicioAsignacion_EnviarEmergencia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicioAsignacionServer is the server API for ServicioAsignacion service.
// All implementations must embed UnimplementedServicioAsignacionServer
// for forward compatibility.
type ServicioAsignacionServer interface {
	EnviarEmergencia(context.Context, *EmergenciaRequest) (*Respuesta, error)
	mustEmbedUnimplementedServicioAsignacionServer()
}

// UnimplementedServicioAsignacionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicioAsignacionServer struct{}

func (UnimplementedServicioAsignacionServer) EnviarEmergencia(context.Context, *EmergenciaRequest) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarEmergencia not implemented")
}
func (UnimplementedServicioAsignacionServer) mustEmbedUnimplementedServicioAsignacionServer() {}
func (UnimplementedServicioAsignacionServer) testEmbeddedByValue()                            {}

// UnsafeServicioAsignacionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioAsignacionServer will
// result in compilation errors.
type UnsafeServicioAsignacionServer interface {
	mustEmbedUnimplementedServicioAsignacionServer()
}

func RegisterServicioAsignacionServer(s grpc.ServiceRegistrar, srv ServicioAsignacionServer) {
	// If the following call pancis, it indicates UnimplementedServicioAsignacionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicioAsignacion_ServiceDesc, srv)
}

func _ServicioAsignacion_EnviarEmergencia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergenciaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioAsignacionServer).EnviarEmergencia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioAsignacion_EnviarEmergencia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioAsignacionServer).EnviarEmergencia(ctx, req.(*EmergenciaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicioAsignacion_ServiceDesc is the grpc.ServiceDesc for ServicioAsignacion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioAsignacion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asignacion.ServicioAsignacion",
	HandlerType: (*ServicioAsignacionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarEmergencia",
			Handler:    _ServicioAsignacion_EnviarEmergencia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asignacion.proto",
}
