// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/monitoreo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClienteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     string                 `protobuf:"bytes,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClienteInfo) Reset() {
	*x = ClienteInfo{}
	mi := &file_proto_monitoreo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClienteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteInfo) ProtoMessage() {}

func (x *ClienteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoreo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteInfo.ProtoReflect.Descriptor instead.
func (*ClienteInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitoreo_proto_rawDescGZIP(), []int{0}
}

func (x *ClienteInfo) GetClienteId() string {
	if x != nil {
		return x.ClienteId
	}
	return ""
}

type EstadoEmergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstadoEmergencia) Reset() {
	*x = EstadoEmergencia{}
	mi := &file_proto_monitoreo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadoEmergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoEmergencia) ProtoMessage() {}

func (x *EstadoEmergencia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitoreo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoEmergencia.ProtoReflect.Descriptor instead.
func (*EstadoEmergencia) Descriptor() ([]byte, []int) {
	return file_proto_monitoreo_proto_rawDescGZIP(), []int{1}
}

func (x *EstadoEmergencia) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *EstadoEmergencia) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_monitoreo_proto protoreflect.FileDescriptor

const file_proto_monitoreo_proto_rawDesc = "" +
	"\n" +
	"\x15proto/monitoreo.proto\x12\tmonitoreo\",\n" +
	"\vClienteInfo\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\tR\tclienteId\"B\n" +
	"\x10EstadoEmergencia\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2c\n" +
	"\x11ServicioMonitoreo\x12N\n" +
	"\x15StreamActualizaciones\x12\x16.monitoreo.ClienteInfo\x1a\x1b.monitoreo.EstadoEmergencia0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_monitoreo_proto_rawDescOnce sync.Once
	file_proto_monitoreo_proto_rawDescData []byte
)

func file_proto_monitoreo_proto_rawDescGZIP() []byte {
	file_proto_monitoreo_proto_rawDescOnce.Do(func() {
		file_proto_monitoreo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitoreo_proto_rawDesc), len(file_proto_monitoreo_proto_rawDesc)))
	})
	return file_proto_monitoreo_proto_rawDescData
}

var file_proto_monitoreo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_monitoreo_proto_goTypes = []any{
	(*ClienteInfo)(nil),      // 0: monitoreo.ClienteInfo
	(*EstadoEmergencia)(nil), // 1: monitoreo.EstadoEmergencia
}
var file_proto_monitoreo_proto_depIdxs = []int32{
	0, // 0: monitoreo.ServicioMonitoreo.StreamActualizaciones:input_type -> monitoreo.ClienteInfo
	1, // 1: monitoreo.ServicioMonitoreo.StreamActualizaciones:output_type -> monitoreo.EstadoEmergencia
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_monitoreo_proto_init() }
func file_proto_monitoreo_proto_init() {
	if File_proto_monitoreo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitoreo_proto_rawDesc), len(file_proto_monitoreo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitoreo_proto_goTypes,
		DependencyIndexes: file_proto_monitoreo_proto_depIdxs,
		MessageInfos:      file_proto_monitoreo_proto_msgTypes,
	}.Build()
	File_proto_monitoreo_proto = out.File
	file_proto_monitoreo_proto_goTypes = nil
	file_proto_monitoreo_proto_depIdxs = nil
}
